from . import student
from . import meal
from . import Reservation
from . import topup
from . import menu
from . import product_category
from . import product_product
from . import gsie_family
from . import res_partner
from . import pos_order_line_payment
from . import credit_agreement_wizard